name: audio_wave
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  record: ^4.4.4
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  assets_audio_player: ^3.0.6
  flutter_styled_toast: ^2.1.3
  audio_waveforms: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.svg